version: "1"
mode: "dev"

server:
  host: "localhost"
  port: "4040"

database:
  user: ""
  pass: ""

eth:
  url:
    http: "https://mainnet.infura.io/v3/e88682fd5b8e46bbb9c4eeb467bb6e63"
    ws: "wss://mainnet.infura.io/ws/v3/"
  user: ""
  pass: ""
