version: "1"
mode: "prod"

server:
  host: "0.0.0.0"
  port: "80"

database:
  user: ""
  pass: ""

eth:
  url:
    http: "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
    ws: "wss://mainnet.infura.io/ws/v3/9aa3d95b3bc440fa88ea12eaa4456161"
  user: ""
  pass: ""
