version: "1"
mode: "prod"

server:
  host: "0.0.0.0"
  port: "4040"

database:
  user: ""
  pass: ""

eth:
  url:
    http: "https://mainnet.infura.io/v3/"
    ws: "wss://mainnet.infura.io/ws/v3/"
  user: ""
  pass: ""

etherscanKey: ""
